// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhoWebV1;

namespace TrabalhoWebV1.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20191125215404_migracao_models")]
    partial class migracao_models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrabalhoWebV1.Models.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataCadastro");

                    b.Property<string>("descricao");

                    b.Property<int>("desenvolvedorCriadorId");

                    b.Property<int>("desenvolvedorResolvedorId");

                    b.Property<string>("prioridade");

                    b.Property<int>("requisitoId");

                    b.Property<bool>("resolvido");

                    b.HasKey("Id");

                    b.HasIndex("desenvolvedorCriadorId");

                    b.HasIndex("desenvolvedorResolvedorId");

                    b.HasIndex("requisitoId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.Desenvolvedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("adm");

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<string>("senha");

                    b.HasKey("Id");

                    b.ToTable("Desenvolvedors");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.DesenvolvedorProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DesenvolvedorId");

                    b.Property<int>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("DesenvolvedorId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("DesenvolvedorProjetos");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.DesenvolvedorRequisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DesenvolvedorId");

                    b.Property<int>("RequisitoId");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoId");

                    b.ToTable("DesenvolverdorRequisitos");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataEntrega");

                    b.Property<string>("nome");

                    b.Property<string>("solicitante");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.Requisito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjetoId");

                    b.Property<DateTime>("dataCadastro");

                    b.Property<DateTime>("dataEntrega");

                    b.Property<string>("descricao");

                    b.Property<bool>("funcional");

                    b.Property<string>("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Requisitos");
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.Bug", b =>
                {
                    b.HasOne("TrabalhoWebV1.Models.Desenvolvedor", "DesenvolvedorCriador")
                        .WithMany("bugCriados")
                        .HasForeignKey("desenvolvedorCriadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrabalhoWebV1.Models.Desenvolvedor", "DesenvolvedorResolvedor")
                        .WithMany("bugResolvidos")
                        .HasForeignKey("desenvolvedorResolvedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrabalhoWebV1.Models.Requisito", "Requisito")
                        .WithMany("Bugs")
                        .HasForeignKey("requisitoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.DesenvolvedorProjeto", b =>
                {
                    b.HasOne("TrabalhoWebV1.Models.Desenvolvedor", "Desenvolvedor")
                        .WithMany()
                        .HasForeignKey("DesenvolvedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrabalhoWebV1.Models.Projeto", "Projeto")
                        .WithMany("DesenvolvedorProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.DesenvolvedorRequisito", b =>
                {
                    b.HasOne("TrabalhoWebV1.Models.Requisito", "Requisito")
                        .WithMany("DesenvolvedorRequisitos")
                        .HasForeignKey("RequisitoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrabalhoWebV1.Models.Requisito", b =>
                {
                    b.HasOne("TrabalhoWebV1.Models.Projeto", "projeto")
                        .WithMany("Requisitos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
